<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.demo</groupId>
        <artifactId>microservice-demo</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>gateway</artifactId>

    <dependencies>
        <!-- gateway 不能用 web，必须用 cloud-gateway 依赖 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

        <!-- gateway 不要直接依赖 user-service，会报错 -->
        <!-- <dependency>
            <groupId>com.demo</groupId>
            <artifactId>user-service</artifactId>
            <version>${project.version}</version>
        </dependency> -->
       <!-- 公共接口依赖 ✅ 正确 -->
        <dependency>
            <groupId>com.demo</groupId>
            <artifactId>api-common</artifactId>
            <version>1.0.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
        	<groupId>com.demo</groupId>
        	<artifactId>user-service</artifactId>
        	<version>1.0.0</version>
        </dependency>
    </dependencies>
</project>